HOSTS:
  icat-puppet-test:
    roles:
      - master
      - agent
    platform: el-7-x86_64
    box: puppetlabs/centos-7.0-64-puppet
    # box_url: TODO: Find the url for this.  At the moment we assume it has
    #          already been downloaded using `vagrant init` on a Vagrantfile
    #          that contains the name of the box.
    hypervisor: vagrant
CONFIG:
  log_level: debug
