HOSTS:
  icat-puppet-test:
    roles:
      - master
      - agent
    platform: el-7-x86_64
    box: puppetlabs/centos-7.0-64-puppet
    box_url: https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-puppet
    hypervisor: vagrant
CONFIG:
  log_level: debug
